import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  tutorialSidebar: [
    {
      'Getting Started': [
      'introduction'
    ],
    'Installing Mixcore': [
      'installation-before-you-install',
      'installation-install-mixcore'
    ],
    'Basic Usage':[
      'basic-usage-first-step-with-mixcore-cms',
      'basic-administration-screens',
      'basic-usage-writing-posts',
      'basic-usage-page',
      'basic-usage-module',
      'basic-usage-navigation',
      'basic-usage-database',
      'basic-usage-category',
      'basic-usage-tag',
      'basic-usage-media',
      'basic-usage-file',
      'basic-usage-user',
      'basic-usage-theme',
      'basic-usage-app-settings',
      'basic-usage-configuration',
      // 'basic-usage-media-library-screen',
      'basic-usage-users-profile'
    ],
    // 'Basic Administration':[
    //   'basic-administration-administration-screens',
    //   'basic-administration-dashboard-sreen',
    //   'basic-administration-roles-and-capabilities'
    // ],
    'Maintenance': [
      'maintenance-mixcore-backups',
      'maintenance-mixcore-restores',
      'maintenance-optimization'
    ],
    'Security': [
      'security-hardening-mixcore',
      'security-brute-force-attacks'
    ],
    'Advanced': [
      'advanced-page-types',
      'advanced-post-types',
      'advanced-module-types',
      'advanced-attribute-sets'
    ],
    'Troubleshooting': [
      'troubleshooting-common-errors',
      'troubleshooting-debugging'
    ],
    'Developers': [
      'dev-getting-started',
    ],
    'Themes': [
      'themes-getting-started',
      'themes-basics',
      'themes-template-files',
      'themes-functionality',
      'themes-release-your-theme'
      // 'customizing-using-themes',
      // 'customizing-using-modules',
      // 'customizing-using-attribute-sets'
    ],
    'Get Involved': [
      'contribute-getting-started',
    ],  
    // Features: ['mdx'],
    },
  ],
   
};

export default sidebars;
