### YamlMime:ManagedReference
items:
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  commentId: T:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  id: GlobalSettingsViewModel
  parent: Mix.Cms.Lib.ViewModels
  children:
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
  - Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
  langs:
  - csharp
  - vb
  name: GlobalSettingsViewModel
  nameWithType: GlobalSettingsViewModel
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  type: Class
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: 'public class GlobalSettingsViewModel : Object'
    content.vb: >-
      Public Class GlobalSettingsViewModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor
  commentId: M:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor
  id: '#ctor'
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: GlobalSettingsViewModel()
  nameWithType: GlobalSettingsViewModel.GlobalSettingsViewModel()
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.GlobalSettingsViewModel()
  type: Constructor
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public GlobalSettingsViewModel()
    content.vb: Public Sub New
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
  id: Lang
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: Lang
  nameWithType: GlobalSettingsViewModel.Lang
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public string Lang { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Lang As String
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
  id: LangIcon
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: LangIcon
  nameWithType: GlobalSettingsViewModel.LangIcon
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public string LangIcon { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LangIcon As String
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
  id: ThemeId
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: ThemeId
  nameWithType: GlobalSettingsViewModel.ThemeId
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public int ThemeId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property ThemeId As Integer
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
  id: ApiEncryptKey
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: ApiEncryptKey
  nameWithType: GlobalSettingsViewModel.ApiEncryptKey
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public string ApiEncryptKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApiEncryptKey As String
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
  id: ApiEncryptIV
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: ApiEncryptIV
  nameWithType: GlobalSettingsViewModel.ApiEncryptIV
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public string ApiEncryptIV { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApiEncryptIV As String
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
  id: IsEncryptApi
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: IsEncryptApi
  nameWithType: GlobalSettingsViewModel.IsEncryptApi
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public bool IsEncryptApi { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property IsEncryptApi As Boolean
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
  id: Cultures
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: Cultures
  nameWithType: GlobalSettingsViewModel.Cultures
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public List<SupportedCulture> Cultures { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Mix.Domain.Core.Models.SupportedCulture}
    content.vb: Public Property Cultures As List(Of SupportedCulture)
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
  id: PageTypes
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: PageTypes
  nameWithType: GlobalSettingsViewModel.PageTypes
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public List<string> PageTypes { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property PageTypes As List(Of String)
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
  commentId: P:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
  id: Statuses
  parent: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel
  langs:
  - csharp
  - vb
  name: Statuses
  nameWithType: GlobalSettingsViewModel.Statuses
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
  type: Property
  source:
    path: Mix.Cms.Lib
    isExternal: true
  assemblies:
  - Mix.Cms.Lib
  namespace: Mix.Cms.Lib.ViewModels
  syntax:
    content: public List<string> Statuses { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property Statuses As List(Of String)
  overload: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Mix.Cms.Lib.ViewModels
  commentId: N:Mix.Cms.Lib.ViewModels
  isExternal: true
  name: Mix.Cms.Lib.ViewModels
  nameWithType: Mix.Cms.Lib.ViewModels
  fullName: Mix.Cms.Lib.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.#ctor
  isExternal: true
  name: GlobalSettingsViewModel
  nameWithType: GlobalSettingsViewModel.GlobalSettingsViewModel
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.GlobalSettingsViewModel
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
  isExternal: true
  name: Lang
  nameWithType: GlobalSettingsViewModel.Lang
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Lang
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
  isExternal: true
  name: LangIcon
  nameWithType: GlobalSettingsViewModel.LangIcon
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.LangIcon
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
  isExternal: true
  name: ThemeId
  nameWithType: GlobalSettingsViewModel.ThemeId
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ThemeId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
  isExternal: true
  name: ApiEncryptKey
  nameWithType: GlobalSettingsViewModel.ApiEncryptKey
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptKey
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
  isExternal: true
  name: ApiEncryptIV
  nameWithType: GlobalSettingsViewModel.ApiEncryptIV
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.ApiEncryptIV
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
  isExternal: true
  name: IsEncryptApi
  nameWithType: GlobalSettingsViewModel.IsEncryptApi
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.IsEncryptApi
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
  isExternal: true
  name: Cultures
  nameWithType: GlobalSettingsViewModel.Cultures
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Cultures
- uid: System.Collections.Generic.List{Mix.Domain.Core.Models.SupportedCulture}
  commentId: '!:System.Collections.Generic.List{Mix.Domain.Core.Models.SupportedCulture}'
  definition: System.Collections.Generic.List`1
  name: List<SupportedCulture>
  nameWithType: List<SupportedCulture>
  fullName: System.Collections.Generic.List<Mix.Domain.Core.Models.SupportedCulture>
  nameWithType.vb: List(Of SupportedCulture)
  fullName.vb: System.Collections.Generic.List(Of Mix.Domain.Core.Models.SupportedCulture)
  name.vb: List(Of SupportedCulture)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Mix.Domain.Core.Models.SupportedCulture
    name: SupportedCulture
    nameWithType: SupportedCulture
    fullName: Mix.Domain.Core.Models.SupportedCulture
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Mix.Domain.Core.Models.SupportedCulture
    name: SupportedCulture
    nameWithType: SupportedCulture
    fullName: Mix.Domain.Core.Models.SupportedCulture
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: System.Collections.Generic.List<>
  nameWithType.vb: List(Of )
  fullName.vb: System.Collections.Generic.List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
  isExternal: true
  name: PageTypes
  nameWithType: GlobalSettingsViewModel.PageTypes
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.PageTypes
- uid: System.Collections.Generic.List{System.String}
  commentId: '!:System.Collections.Generic.List{System.String}'
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses*
  commentId: Overload:Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
  isExternal: true
  name: Statuses
  nameWithType: GlobalSettingsViewModel.Statuses
  fullName: Mix.Cms.Lib.ViewModels.GlobalSettingsViewModel.Statuses
