### YamlMime:ManagedReference
items:
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  commentId: T:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  id: ConfigureTwoFactorViewModel
  parent: Mix.Identity.Models.ManageViewModels
  children:
  - Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor
  - Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
  - Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
  langs:
  - csharp
  - vb
  name: ConfigureTwoFactorViewModel
  nameWithType: ConfigureTwoFactorViewModel
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  type: Class
  source:
    path: Mix.Identity
    isExternal: true
  assemblies:
  - Mix.Identity
  namespace: Mix.Identity.Models.ManageViewModels
  syntax:
    content: 'public class ConfigureTwoFactorViewModel : Object'
    content.vb: >-
      Public Class ConfigureTwoFactorViewModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor
  commentId: M:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor
  id: '#ctor'
  parent: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  langs:
  - csharp
  - vb
  name: ConfigureTwoFactorViewModel()
  nameWithType: ConfigureTwoFactorViewModel.ConfigureTwoFactorViewModel()
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.ConfigureTwoFactorViewModel()
  type: Constructor
  source:
    path: Mix.Identity
    isExternal: true
  assemblies:
  - Mix.Identity
  namespace: Mix.Identity.Models.ManageViewModels
  syntax:
    content: public ConfigureTwoFactorViewModel()
    content.vb: Public Sub New
  overload: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
  commentId: P:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
  id: SelectedProvider
  parent: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  langs:
  - csharp
  - vb
  name: SelectedProvider
  nameWithType: ConfigureTwoFactorViewModel.SelectedProvider
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
  type: Property
  source:
    path: Mix.Identity
    isExternal: true
  assemblies:
  - Mix.Identity
  namespace: Mix.Identity.Models.ManageViewModels
  syntax:
    content: public string SelectedProvider { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property SelectedProvider As String
  overload: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
  commentId: P:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
  id: Providers
  parent: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel
  langs:
  - csharp
  - vb
  name: Providers
  nameWithType: ConfigureTwoFactorViewModel.Providers
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
  type: Property
  source:
    path: Mix.Identity
    isExternal: true
  assemblies:
  - Mix.Identity
  namespace: Mix.Identity.Models.ManageViewModels
  syntax:
    content: public ICollection<SelectListItem> Providers { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.ICollection{Microsoft.AspNetCore.Mvc.Rendering.SelectListItem}
    content.vb: Public Property Providers As ICollection(Of SelectListItem)
  overload: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Mix.Identity.Models.ManageViewModels
  commentId: N:Mix.Identity.Models.ManageViewModels
  isExternal: true
  name: Mix.Identity.Models.ManageViewModels
  nameWithType: Mix.Identity.Models.ManageViewModels
  fullName: Mix.Identity.Models.ManageViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor*
  commentId: Overload:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.#ctor
  isExternal: true
  name: ConfigureTwoFactorViewModel
  nameWithType: ConfigureTwoFactorViewModel.ConfigureTwoFactorViewModel
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.ConfigureTwoFactorViewModel
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider*
  commentId: Overload:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
  isExternal: true
  name: SelectedProvider
  nameWithType: ConfigureTwoFactorViewModel.SelectedProvider
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.SelectedProvider
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers*
  commentId: Overload:Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
  isExternal: true
  name: Providers
  nameWithType: ConfigureTwoFactorViewModel.Providers
  fullName: Mix.Identity.Models.ManageViewModels.ConfigureTwoFactorViewModel.Providers
- uid: System.Collections.Generic.ICollection{Microsoft.AspNetCore.Mvc.Rendering.SelectListItem}
  commentId: '!:System.Collections.Generic.ICollection{Microsoft.AspNetCore.Mvc.Rendering.SelectListItem}'
  definition: System.Collections.Generic.ICollection`1
  name: ICollection<SelectListItem>
  nameWithType: ICollection<SelectListItem>
  fullName: System.Collections.Generic.ICollection<Microsoft.AspNetCore.Mvc.Rendering.SelectListItem>
  nameWithType.vb: ICollection(Of SelectListItem)
  fullName.vb: System.Collections.Generic.ICollection(Of Microsoft.AspNetCore.Mvc.Rendering.SelectListItem)
  name.vb: ICollection(Of SelectListItem)
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
    name: SelectListItem
    nameWithType: SelectListItem
    fullName: Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
    name: SelectListItem
    nameWithType: SelectListItem
    fullName: Microsoft.AspNetCore.Mvc.Rendering.SelectListItem
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.ICollection`1
  isExternal: true
  name: ICollection<>
  nameWithType: ICollection<>
  fullName: System.Collections.Generic.ICollection<>
  nameWithType.vb: ICollection(Of )
  fullName.vb: System.Collections.Generic.ICollection(Of )
  name.vb: ICollection(Of )
  spec.csharp:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.ICollection`1
    name: ICollection
    nameWithType: ICollection
    fullName: System.Collections.Generic.ICollection
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
