### YamlMime:ManagedReference
items:
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType
  commentId: T:Swastika.Cms.Lib.SWCmsConstants.ConfigurationType
  id: SWCmsConstants.ConfigurationType
  parent: Swastika.Cms.Lib
  children:
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.System
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.User
  langs:
  - csharp
  - vb
  name: SWCmsConstants.ConfigurationType
  nameWithType: SWCmsConstants.ConfigurationType
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType
  type: Class
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: 'public static class ConfigurationType : Object'
    content.vb: >-
      Public Module ConfigurationType
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.System
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.System
  id: System
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType
  langs:
  - csharp
  - vb
  name: System
  nameWithType: SWCmsConstants.ConfigurationType.System
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.System
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const string System = "System"
    return:
      type: System.String
    content.vb: Public Const System As String = "System"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.User
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.User
  id: User
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType
  langs:
  - csharp
  - vb
  name: User
  nameWithType: SWCmsConstants.ConfigurationType.User
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationType.User
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const string User = "User"
    return:
      type: System.String
    content.vb: Public Const User As String = "User"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Swastika.Cms.Lib
  commentId: N:Swastika.Cms.Lib
  isExternal: true
  name: Swastika.Cms.Lib
  nameWithType: Swastika.Cms.Lib
  fullName: Swastika.Cms.Lib
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
