### YamlMime:ManagedReference
items:
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  commentId: T:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  id: SWCmsConstants.ConfigurationCategory
  parent: Swastika.Cms.Lib
  children:
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Email
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.PageSize
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Site
  - Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.value__
  langs:
  - csharp
  - vb
  name: SWCmsConstants.ConfigurationCategory
  nameWithType: SWCmsConstants.ConfigurationCategory
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  type: Class
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: 'public sealed class ConfigurationCategory : Enum'
    content.vb: >-
      Public NotInheritable Class ConfigurationCategory
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.value__
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.value__
  id: value__
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: SWCmsConstants.ConfigurationCategory.value__
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.value__
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.PageSize
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.PageSize
  id: PageSize
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  langs:
  - csharp
  - vb
  name: PageSize
  nameWithType: SWCmsConstants.ConfigurationCategory.PageSize
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.PageSize
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const SWCmsConstants.ConfigurationCategory PageSize
    return:
      type: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
    content.vb: Public Const PageSize As SWCmsConstants.ConfigurationCategory
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Site
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Site
  id: Site
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  langs:
  - csharp
  - vb
  name: Site
  nameWithType: SWCmsConstants.ConfigurationCategory.Site
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Site
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const SWCmsConstants.ConfigurationCategory Site
    return:
      type: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
    content.vb: Public Const Site As SWCmsConstants.ConfigurationCategory
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Email
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Email
  id: Email
  parent: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  langs:
  - csharp
  - vb
  name: Email
  nameWithType: SWCmsConstants.ConfigurationCategory.Email
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory.Email
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const SWCmsConstants.ConfigurationCategory Email
    return:
      type: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
    content.vb: Public Const Email As SWCmsConstants.ConfigurationCategory
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Swastika.Cms.Lib
  commentId: N:Swastika.Cms.Lib
  isExternal: true
  name: Swastika.Cms.Lib
  nameWithType: Swastika.Cms.Lib
  fullName: Swastika.Cms.Lib
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  commentId: T:Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
  parent: Swastika.Cms.Lib
  isExternal: true
  name: SWCmsConstants.ConfigurationCategory
  nameWithType: SWCmsConstants.ConfigurationCategory
  fullName: Swastika.Cms.Lib.SWCmsConstants.ConfigurationCategory
