### YamlMime:ManagedReference
items:
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  commentId: T:Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  id: SiocConfiguration
  parent: Swastika.Cms.Lib.Models.Cms
  children:
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
  - Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
  langs:
  - csharp
  - vb
  name: SiocConfiguration
  nameWithType: SiocConfiguration
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  type: Class
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: 'public class SiocConfiguration : Object'
    content.vb: >-
      Public Class SiocConfiguration
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor
  commentId: M:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor
  id: '#ctor'
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: SiocConfiguration()
  nameWithType: SiocConfiguration.SiocConfiguration()
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SiocConfiguration()
  type: Constructor
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public SiocConfiguration()
    content.vb: Public Sub New
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
  id: Keyword
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Keyword
  nameWithType: SiocConfiguration.Keyword
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public string Keyword { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Keyword As String
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
  id: Specificulture
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Specificulture
  nameWithType: SiocConfiguration.Specificulture
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public string Specificulture { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Specificulture As String
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
  id: Category
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Category
  nameWithType: SiocConfiguration.Category
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public string Category { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Category As String
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
  id: DataType
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: DataType
  nameWithType: SiocConfiguration.DataType
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public int DataType { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property DataType As Integer
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
  id: Description
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Description
  nameWithType: SiocConfiguration.Description
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public string Description { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Description As String
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
  id: Priority
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Priority
  nameWithType: SiocConfiguration.Priority
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public int Priority { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Priority As Integer
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
  id: Status
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Status
  nameWithType: SiocConfiguration.Status
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public int Status { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Status As Integer
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
  id: Value
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: SiocConfiguration.Value
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public string Value { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Value As String
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
  commentId: P:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
  id: SpecificultureNavigation
  parent: Swastika.Cms.Lib.Models.Cms.SiocConfiguration
  langs:
  - csharp
  - vb
  name: SpecificultureNavigation
  nameWithType: SiocConfiguration.SpecificultureNavigation
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.Models.Cms
  syntax:
    content: public SiocCulture SpecificultureNavigation { get; set; }
    parameters: []
    return:
      type: Swastika.Cms.Lib.Models.Cms.SiocCulture
    content.vb: Public Property SpecificultureNavigation As SiocCulture
  overload: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Swastika.Cms.Lib.Models.Cms
  commentId: N:Swastika.Cms.Lib.Models.Cms
  isExternal: true
  name: Swastika.Cms.Lib.Models.Cms
  nameWithType: Swastika.Cms.Lib.Models.Cms
  fullName: Swastika.Cms.Lib.Models.Cms
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.#ctor
  isExternal: true
  name: SiocConfiguration
  nameWithType: SiocConfiguration.SiocConfiguration
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SiocConfiguration
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
  isExternal: true
  name: Keyword
  nameWithType: SiocConfiguration.Keyword
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Keyword
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
  isExternal: true
  name: Specificulture
  nameWithType: SiocConfiguration.Specificulture
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Specificulture
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
  isExternal: true
  name: Category
  nameWithType: SiocConfiguration.Category
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Category
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
  isExternal: true
  name: DataType
  nameWithType: SiocConfiguration.DataType
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.DataType
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
  isExternal: true
  name: Description
  nameWithType: SiocConfiguration.Description
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Description
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
  isExternal: true
  name: Priority
  nameWithType: SiocConfiguration.Priority
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Priority
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
  isExternal: true
  name: Status
  nameWithType: SiocConfiguration.Status
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Status
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
  isExternal: true
  name: Value
  nameWithType: SiocConfiguration.Value
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.Value
- uid: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation*
  commentId: Overload:Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
  isExternal: true
  name: SpecificultureNavigation
  nameWithType: SiocConfiguration.SpecificultureNavigation
  fullName: Swastika.Cms.Lib.Models.Cms.SiocConfiguration.SpecificultureNavigation
- uid: Swastika.Cms.Lib.Models.Cms.SiocCulture
  commentId: T:Swastika.Cms.Lib.Models.Cms.SiocCulture
  parent: Swastika.Cms.Lib.Models.Cms
  isExternal: true
  name: SiocCulture
  nameWithType: SiocCulture
  fullName: Swastika.Cms.Lib.Models.Cms.SiocCulture
