### YamlMime:ManagedReference
items:
- uid: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  commentId: T:Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  id: SWCmsConstants.JwtSettings
  parent: Swastika.Cms.Lib
  children:
  - Swastika.Cms.Lib.SWCmsConstants.JwtSettings.AUDIENCE
  - Swastika.Cms.Lib.SWCmsConstants.JwtSettings.EXPIRED_IN
  - Swastika.Cms.Lib.SWCmsConstants.JwtSettings.ISSUER
  - Swastika.Cms.Lib.SWCmsConstants.JwtSettings.SECRET_KEY
  langs:
  - csharp
  - vb
  name: SWCmsConstants.JwtSettings
  nameWithType: SWCmsConstants.JwtSettings
  fullName: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  type: Class
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: 'public static class JwtSettings : Object'
    content.vb: >-
      Public Module JwtSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.AUDIENCE
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.JwtSettings.AUDIENCE
  id: AUDIENCE
  parent: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  langs:
  - csharp
  - vb
  name: AUDIENCE
  nameWithType: SWCmsConstants.JwtSettings.AUDIENCE
  fullName: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.AUDIENCE
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const string AUDIENCE = "http://localhost:58510/"
    return:
      type: System.String
    content.vb: Public Const AUDIENCE As String = "http://localhost:58510/"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.EXPIRED_IN
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.JwtSettings.EXPIRED_IN
  id: EXPIRED_IN
  parent: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  langs:
  - csharp
  - vb
  name: EXPIRED_IN
  nameWithType: SWCmsConstants.JwtSettings.EXPIRED_IN
  fullName: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.EXPIRED_IN
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const int EXPIRED_IN = 10
    return:
      type: System.Int32
    content.vb: Public Const EXPIRED_IN As Integer = 10
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.ISSUER
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.JwtSettings.ISSUER
  id: ISSUER
  parent: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  langs:
  - csharp
  - vb
  name: ISSUER
  nameWithType: SWCmsConstants.JwtSettings.ISSUER
  fullName: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.ISSUER
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const string ISSUER = "http://localhost:58510/"
    return:
      type: System.String
    content.vb: Public Const ISSUER As String = "http://localhost:58510/"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.SECRET_KEY
  commentId: F:Swastika.Cms.Lib.SWCmsConstants.JwtSettings.SECRET_KEY
  id: SECRET_KEY
  parent: Swastika.Cms.Lib.SWCmsConstants.JwtSettings
  langs:
  - csharp
  - vb
  name: SECRET_KEY
  nameWithType: SWCmsConstants.JwtSettings.SECRET_KEY
  fullName: Swastika.Cms.Lib.SWCmsConstants.JwtSettings.SECRET_KEY
  type: Field
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib
  syntax:
    content: public const string SECRET_KEY = "swastika-secret-key"
    return:
      type: System.String
    content.vb: Public Const SECRET_KEY As String = "swastika-secret-key"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Swastika.Cms.Lib
  commentId: N:Swastika.Cms.Lib
  isExternal: true
  name: Swastika.Cms.Lib
  nameWithType: Swastika.Cms.Lib
  fullName: Swastika.Cms.Lib
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
