### YamlMime:ManagedReference
items:
- uid: Swastika.Identity.Const.ApplicationTypes
  commentId: T:Swastika.Identity.Const.ApplicationTypes
  id: Const.ApplicationTypes
  parent: Swastika.Identity
  children:
  - Swastika.Identity.Const.ApplicationTypes.JavaScript
  - Swastika.Identity.Const.ApplicationTypes.NativeConfidential
  - Swastika.Identity.Const.ApplicationTypes.value__
  langs:
  - csharp
  - vb
  name: Const.ApplicationTypes
  nameWithType: Const.ApplicationTypes
  fullName: Swastika.Identity.Const.ApplicationTypes
  type: Class
  source:
    path: Swastika.Identity
    isExternal: true
  assemblies:
  - Swastika.Identity
  namespace: Swastika.Identity
  syntax:
    content: 'public sealed class ApplicationTypes : Enum'
    content.vb: >-
      Public NotInheritable Class ApplicationTypes
          Inherits

           Enum
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: Swastika.Identity.Const.ApplicationTypes.value__
  commentId: F:Swastika.Identity.Const.ApplicationTypes.value__
  id: value__
  parent: Swastika.Identity.Const.ApplicationTypes
  langs:
  - csharp
  - vb
  name: value__
  nameWithType: Const.ApplicationTypes.value__
  fullName: Swastika.Identity.Const.ApplicationTypes.value__
  type: Field
  source:
    path: Swastika.Identity
    isExternal: true
  assemblies:
  - Swastika.Identity
  namespace: Swastika.Identity
  syntax:
    content: public int value__
    return:
      type: System.Int32
    content.vb: Public value__ As Integer
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Swastika.Identity.Const.ApplicationTypes.JavaScript
  commentId: F:Swastika.Identity.Const.ApplicationTypes.JavaScript
  id: JavaScript
  parent: Swastika.Identity.Const.ApplicationTypes
  langs:
  - csharp
  - vb
  name: JavaScript
  nameWithType: Const.ApplicationTypes.JavaScript
  fullName: Swastika.Identity.Const.ApplicationTypes.JavaScript
  type: Field
  source:
    path: Swastika.Identity
    isExternal: true
  assemblies:
  - Swastika.Identity
  namespace: Swastika.Identity
  syntax:
    content: public const Const.ApplicationTypes JavaScript
    return:
      type: Swastika.Identity.Const.ApplicationTypes
    content.vb: 'Public Const JavaScript As '
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Swastika.Identity.Const.ApplicationTypes.NativeConfidential
  commentId: F:Swastika.Identity.Const.ApplicationTypes.NativeConfidential
  id: NativeConfidential
  parent: Swastika.Identity.Const.ApplicationTypes
  langs:
  - csharp
  - vb
  name: NativeConfidential
  nameWithType: Const.ApplicationTypes.NativeConfidential
  fullName: Swastika.Identity.Const.ApplicationTypes.NativeConfidential
  type: Field
  source:
    path: Swastika.Identity
    isExternal: true
  assemblies:
  - Swastika.Identity
  namespace: Swastika.Identity
  syntax:
    content: public const Const.ApplicationTypes NativeConfidential
    return:
      type: Swastika.Identity.Const.ApplicationTypes
    content.vb: 'Public Const NativeConfidential As '
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Swastika.Identity
  commentId: N:Swastika.Identity
  isExternal: true
  name: Swastika.Identity
  nameWithType: Swastika.Identity
  fullName: Swastika.Identity
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Swastika.Identity.Const.ApplicationTypes
  commentId: T:Swastika.Identity.Const.ApplicationTypes
  parent: Swastika.Identity
  isExternal: true
  name: Const.ApplicationTypes
  nameWithType: Const.ApplicationTypes
  fullName: Swastika.Identity.Const.ApplicationTypes
