### YamlMime:ManagedReference
items:
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  commentId: T:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  id: SiteSettingsViewModel
  parent: Swastika.Cms.Lib.ViewModels
  children:
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
  - Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
  langs:
  - csharp
  - vb
  name: SiteSettingsViewModel
  nameWithType: SiteSettingsViewModel
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  type: Class
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: 'public class SiteSettingsViewModel : Object'
    content.vb: >-
      Public Class SiteSettingsViewModel
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor
  commentId: M:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor
  id: '#ctor'
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: SiteSettingsViewModel()
  nameWithType: SiteSettingsViewModel.SiteSettingsViewModel()
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.SiteSettingsViewModel()
  type: Constructor
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public SiteSettingsViewModel()
    content.vb: Public Sub New
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
  commentId: P:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
  id: Lang
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: Lang
  nameWithType: SiteSettingsViewModel.Lang
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public string Lang { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Lang As String
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
  commentId: P:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
  id: LangIcon
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: LangIcon
  nameWithType: SiteSettingsViewModel.LangIcon
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public string LangIcon { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LangIcon As String
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
  commentId: P:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
  id: ThemeId
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: ThemeId
  nameWithType: SiteSettingsViewModel.ThemeId
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public int ThemeId { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property ThemeId As Integer
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
  commentId: P:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
  id: Cultures
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: Cultures
  nameWithType: SiteSettingsViewModel.Cultures
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public List<SupportedCulture> Cultures { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{Swastika.Domain.Core.Models.SupportedCulture}
    content.vb: Public Property Cultures As List(Of SupportedCulture)
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
  commentId: P:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
  id: PageTypes
  parent: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel
  langs:
  - csharp
  - vb
  name: PageTypes
  nameWithType: SiteSettingsViewModel.PageTypes
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
  type: Property
  source:
    path: Swastika.Cms.Lib
    isExternal: true
  assemblies:
  - Swastika.Cms.Lib
  namespace: Swastika.Cms.Lib.ViewModels
  syntax:
    content: public List<string> PageTypes { get; set; }
    parameters: []
    return:
      type: System.Collections.Generic.List{System.String}
    content.vb: Public Property PageTypes As List(Of String)
  overload: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Swastika.Cms.Lib.ViewModels
  commentId: N:Swastika.Cms.Lib.ViewModels
  isExternal: true
  name: Swastika.Cms.Lib.ViewModels
  nameWithType: Swastika.Cms.Lib.ViewModels
  fullName: Swastika.Cms.Lib.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.#ctor
  isExternal: true
  name: SiteSettingsViewModel
  nameWithType: SiteSettingsViewModel.SiteSettingsViewModel
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.SiteSettingsViewModel
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
  isExternal: true
  name: Lang
  nameWithType: SiteSettingsViewModel.Lang
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Lang
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
  isExternal: true
  name: LangIcon
  nameWithType: SiteSettingsViewModel.LangIcon
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.LangIcon
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
  isExternal: true
  name: ThemeId
  nameWithType: SiteSettingsViewModel.ThemeId
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.ThemeId
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
  isExternal: true
  name: Cultures
  nameWithType: SiteSettingsViewModel.Cultures
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.Cultures
- uid: System.Collections.Generic.List{Swastika.Domain.Core.Models.SupportedCulture}
  commentId: '!:System.Collections.Generic.List{Swastika.Domain.Core.Models.SupportedCulture}'
  definition: System.Collections.Generic.List`1
  name: List<SupportedCulture>
  nameWithType: List<SupportedCulture>
  fullName: System.Collections.Generic.List<Swastika.Domain.Core.Models.SupportedCulture>
  nameWithType.vb: List(Of SupportedCulture)
  fullName.vb: System.Collections.Generic.List(Of Swastika.Domain.Core.Models.SupportedCulture)
  name.vb: List(Of SupportedCulture)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Swastika.Domain.Core.Models.SupportedCulture
    name: SupportedCulture
    nameWithType: SupportedCulture
    fullName: Swastika.Domain.Core.Models.SupportedCulture
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Swastika.Domain.Core.Models.SupportedCulture
    name: SupportedCulture
    nameWithType: SupportedCulture
    fullName: Swastika.Domain.Core.Models.SupportedCulture
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.List`1
  isExternal: true
  name: List<>
  nameWithType: List<>
  fullName: System.Collections.Generic.List<>
  nameWithType.vb: List(Of )
  fullName.vb: System.Collections.Generic.List(Of )
  name.vb: List(Of )
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes*
  commentId: Overload:Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
  isExternal: true
  name: PageTypes
  nameWithType: SiteSettingsViewModel.PageTypes
  fullName: Swastika.Cms.Lib.ViewModels.SiteSettingsViewModel.PageTypes
- uid: System.Collections.Generic.List{System.String}
  commentId: '!:System.Collections.Generic.List{System.String}'
  definition: System.Collections.Generic.List`1
  name: List<String>
  nameWithType: List<String>
  fullName: System.Collections.Generic.List<System.String>
  nameWithType.vb: List(Of String)
  fullName.vb: System.Collections.Generic.List(Of System.String)
  name.vb: List(Of String)
  spec.csharp:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.List`1
    name: List
    nameWithType: List
    fullName: System.Collections.Generic.List
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
